apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-jenkinstest
  labels:
    app: helm-jenkinstest
    chart: helm-jenkinstest
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: helm-jenkinstest
  template:
    metadata:
      labels:
        app: helm-jenkinstest
    spec:
      containers:
        - name: helm-jenkinstest
          image: registry.hub.docker.com/jkjisha/mynginx_image1:v2-release
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 1056Mi
            requests:
              memory: 1028Mi
          affinity: {}
          tolerations: {}
