apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-jenkinstest
  labels:
    app: helm-jenkinstest
    chart: helm-jenkinstest
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: helm-jenkinstest
  template:
    metadata:
      labels:
        app: helm-jenkinstest
    spec:
      containers:
        - name: helm-jenkinstest
          image: registry.hub.docker.com/jkjisha/jenkinstest:3
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: 3056Mi
            requests:
              memory: 2028Mi
          affinity: {}
          tolerations: {}
