apiVersion: v1
kind: Service
metadata:
  name: helm-jenkinstest
  labels:
    app: helm-jenkinstest
    chart: helm-jenkinstest
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: helm-jenkinstest
